# -*- coding: utf-8 -*-
"""
Spyder Editor

This file takes text files generated by 3DEC and converts
them into a form readable by MATLAB
"""

import glob
import numpy as np

def parse_crack(path):
    
    crack_files = glob.glob(path+'*_crack.dat')
    filenames= []
    filenames = [f.replace('_crack.dat','') for f in crack_files]
    
    for filename in filenames:
        fid = open(filename+'_crack.dat', 'r+') #open the crack file
        txt = fid.read() #read the file
        fid.close()
        txt = txt.replace('(',' ').replace(')',' ').replace(',',' ').replace(';',' ').replace('\n',' \n ') # remove extra characters
        dat = np.fromstring(txt,sep=' \n')[:-1] # ask numpy to convert string to array
        all_dat = np.reshape(dat[:],(-1,8)) # reshape array from 1D to 2D #-1 means "dont care how long it is, just make n columns"
        unq_dat = np.vstack({tuple(row) for row in all_dat[:,1:]})
        np.savetxt(filename+'_roundpy.dat',unq_dat,fmt='%f %f %f %f %.3f %.3f %.3f')
        
path = 'C:/Users/Rebecca Napolitano/Documents/datafiles/labWalls/A_simulations/2018_4_25_settlement/test/' #make sure to change
parse_crack(path)